name: test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-activemq:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # The tls tests require keytool to generate a keystore, hence the
      # openjdk-11-jre-headless installation.
      - name: Install Java
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre-headless

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Integration test with activemq classic
        run: make test
